CREATE TABLE :schema_name.SUPPLIER 
(S_SUPPKEY INT,
S_NAME CHAR(25),
S_ADDRESS VARCHAR(40),
S_NATIONKEY INTEGER,
S_PHONE CHAR(15),
S_ACCTBAL DECIMAL(15,2),
S_COMMENT VARCHAR(101),
dummy text);
ALTER TABLE :schema_name.supplier ADD PRIMARY KEY (s_suppkey);
